# Generated by Django 4.2.5 on 2023-10-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_name_product_album_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='album_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
    ]
